// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewsWisePlatform.Models;

#nullable disable

namespace NewsWisePlatform.Migrations
{
    [DbContext(typeof(NewsWiseDbContext))]
    [Migration("20240305221753_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NewsWisePlatform.Models.Admin", b =>
                {
                    b.Property<Guid>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AdminID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("NewsWisePlatform.Models.Comment", b =>
                {
                    b.Property<Guid>("CommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("NewsItemID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("SentimentScore")
                        .HasColumnType("real");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CommentID");

                    b.HasIndex("NewsItemID");

                    b.HasIndex("UserID");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("NewsWisePlatform.Models.CommentFlag", b =>
                {
                    b.Property<Guid>("CommentFlagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CommentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FlaggedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CommentFlagID");

                    b.HasIndex("CommentID")
                        .IsUnique();

                    b.HasIndex("UserID");

                    b.ToTable("CommentFlags");
                });

            modelBuilder.Entity("NewsWisePlatform.Models.EmailNotification", b =>
                {
                    b.Property<Guid>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NotificationID");

                    b.ToTable("EmailNotifications");
                });

            modelBuilder.Entity("NewsWisePlatform.Models.ExternalLogin", b =>
                {
                    b.Property<Guid>("ExternalLoginID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ExternalLoginID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("ExternalLogins");
                });

            modelBuilder.Entity("NewsWisePlatform.Models.MediaAttachment", b =>
                {
                    b.Property<Guid>("MediaAttachmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("NewsItemID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MediaAttachmentID");

                    b.HasIndex("NewsItemID");

                    b.ToTable("MediaAttachments");
                });

            modelBuilder.Entity("NewsWisePlatform.Models.NewsItem", b =>
                {
                    b.Property<Guid>("NewsItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PositivityScore")
                        .HasColumnType("real");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SourceID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NewsItemID");

                    b.ToTable("NewsItems");
                });

            modelBuilder.Entity("NewsWisePlatform.Models.NewsItemBookmark", b =>
                {
                    b.Property<Guid>("BookmarkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NewsItemID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BookmarkID");

                    b.HasIndex("NewsItemID");

                    b.HasIndex("UserID");

                    b.ToTable("NewsItemBookmarks");
                });

            modelBuilder.Entity("NewsWisePlatform.Models.NewsItemLike", b =>
                {
                    b.Property<Guid>("NewsItemLikeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LikedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NewsItemID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NewsItemLikeID");

                    b.HasIndex("NewsItemID");

                    b.HasIndex("UserID");

                    b.ToTable("NewsItemLikes");
                });

            modelBuilder.Entity("NewsWisePlatform.Models.NewsItemShare", b =>
                {
                    b.Property<Guid>("ShareID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NewsItemID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SharedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ShareID");

                    b.HasIndex("NewsItemID");

                    b.HasIndex("UserID");

                    b.ToTable("NewsItemShares");
                });

            modelBuilder.Entity("NewsWisePlatform.Models.NewsItemTopic", b =>
                {
                    b.Property<Guid>("NewsItemID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TopicID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NewsItemID", "TopicID");

                    b.HasIndex("TopicID");

                    b.ToTable("NewsItemTopics");
                });

            modelBuilder.Entity("NewsWisePlatform.Models.NewsSource", b =>
                {
                    b.Property<Guid>("SourceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SourceID");

                    b.ToTable("NewsSources");
                });

            modelBuilder.Entity("NewsWisePlatform.Models.Topic", b =>
                {
                    b.Property<Guid>("TopicID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TopicID");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("NewsWisePlatform.Models.User", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NewsWisePlatform.Models.UserPreference", b =>
                {
                    b.Property<Guid>("PreferenceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("PositivityPreference")
                        .HasColumnType("real");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PreferenceID");

                    b.HasIndex("UserId");

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("NewsWisePlatform.Models.Admin", b =>
                {
                    b.HasOne("NewsWisePlatform.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("NewsWisePlatform.Models.Admin", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NewsWisePlatform.Models.Comment", b =>
                {
                    b.HasOne("NewsWisePlatform.Models.NewsItem", "NewsItem")
                        .WithMany("Comments")
                        .HasForeignKey("NewsItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewsWisePlatform.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewsItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NewsWisePlatform.Models.CommentFlag", b =>
                {
                    b.HasOne("NewsWisePlatform.Models.Comment", "Comment")
                        .WithOne("Flag")
                        .HasForeignKey("NewsWisePlatform.Models.CommentFlag", "CommentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewsWisePlatform.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NewsWisePlatform.Models.ExternalLogin", b =>
                {
                    b.HasOne("NewsWisePlatform.Models.User", "User")
                        .WithOne("ExternalLogin")
                        .HasForeignKey("NewsWisePlatform.Models.ExternalLogin", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NewsWisePlatform.Models.MediaAttachment", b =>
                {
                    b.HasOne("NewsWisePlatform.Models.NewsItem", "NewsItem")
                        .WithMany("MediaAttachments")
                        .HasForeignKey("NewsItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewsItem");
                });

            modelBuilder.Entity("NewsWisePlatform.Models.NewsItemBookmark", b =>
                {
                    b.HasOne("NewsWisePlatform.Models.NewsItem", "NewsItem")
                        .WithMany("Bookmarks")
                        .HasForeignKey("NewsItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewsWisePlatform.Models.User", "User")
                        .WithMany("NewsItemBookmarks")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewsItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NewsWisePlatform.Models.NewsItemLike", b =>
                {
                    b.HasOne("NewsWisePlatform.Models.NewsItem", "NewsItem")
                        .WithMany("Likes")
                        .HasForeignKey("NewsItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewsWisePlatform.Models.User", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewsItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NewsWisePlatform.Models.NewsItemShare", b =>
                {
                    b.HasOne("NewsWisePlatform.Models.NewsItem", "NewsItem")
                        .WithMany("Shares")
                        .HasForeignKey("NewsItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewsWisePlatform.Models.User", "User")
                        .WithMany("NewsItemShares")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewsItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NewsWisePlatform.Models.NewsItemTopic", b =>
                {
                    b.HasOne("NewsWisePlatform.Models.NewsItem", "NewsItem")
                        .WithMany("NewsItemTopics")
                        .HasForeignKey("NewsItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewsWisePlatform.Models.Topic", "Topic")
                        .WithMany("NewsItemTopics")
                        .HasForeignKey("TopicID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewsItem");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("NewsWisePlatform.Models.UserPreference", b =>
                {
                    b.HasOne("NewsWisePlatform.Models.User", null)
                        .WithMany("UserPreferences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NewsWisePlatform.Models.Comment", b =>
                {
                    b.Navigation("Flag")
                        .IsRequired();
                });

            modelBuilder.Entity("NewsWisePlatform.Models.NewsItem", b =>
                {
                    b.Navigation("Bookmarks");

                    b.Navigation("Comments");

                    b.Navigation("Likes");

                    b.Navigation("MediaAttachments");

                    b.Navigation("NewsItemTopics");

                    b.Navigation("Shares");
                });

            modelBuilder.Entity("NewsWisePlatform.Models.Topic", b =>
                {
                    b.Navigation("NewsItemTopics");
                });

            modelBuilder.Entity("NewsWisePlatform.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("ExternalLogin")
                        .IsRequired();

                    b.Navigation("Likes");

                    b.Navigation("NewsItemBookmarks");

                    b.Navigation("NewsItemShares");

                    b.Navigation("UserPreferences");
                });
#pragma warning restore 612, 618
        }
    }
}
